version: '3.8'

services:
  scribe-engine:
    image: ghcr.io/docdimy/scribe-engine:latest
    container_name: scribe-engine-api
    ports:
      - "3001:3001"
    environment:
      - ENVIRONMENT=production
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - RATE_LIMIT_REQUESTS=10
      - MAX_AUDIO_DURATION=600
      - LLM_MAX_TOKENS=2000
      - MAX_FILE_SIZE_MB=50
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis:
    container_name: scribe-engine-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data: 