version: '3.8'

services:
  scribe-engine:
    container_name: scribe-engine-api
    build: .
    ports:
      - "3001:3001"
    environment:
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=DEBUG
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY:-dev-secret-key}
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    restart: unless-stopped

  redis:
    container_name: scribe-engine-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  prometheus:
    container_name: scribe-engine-prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

volumes:
  redis_data: 