version: '3.8'

services:
  # Lokale Docker Registry auf Synology
  registry:
    image: registry:2
    container_name: local-docker-registry
    ports:
      - "5000:5000"
    volumes:
      - /volume1/docker/registry:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
    restart: unless-stopped

  # Registry UI (optional, zum Verwalten)
  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    ports:
      - "5001:80"
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Synology Docker Registry
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    depends_on:
      - registry
    restart: unless-stopped 