version: '3.8'

services:
  scribe-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: scribe-engine:dev
    container_name: scribe-engine-dev
    ports:
      - "3001:3001"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
      - ./audio_files:/app/audio_files
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - DATA_ENCRYPTION_KEY=${DATA_ENCRYPTION_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    networks:
      - scribe-network

  prometheus:
    container_name: scribe-engine-prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - scribe-network

networks:
  scribe-network:
    driver: bridge