version: '3.8'

services:
  scribe-engine-develop:
    build:
      context: .
      dockerfile: Dockerfile
    image: scribe-engine:develop
    container_name: scribe-engine-develop
    ports:
      - "3002:3001"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
      - ./audio_files:/app/audio_files
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - DATA_ENCRYPTION_KEY=${DATA_ENCRYPTION_KEY}
      - RATE_LIMIT_REQUESTS=10
      - MAX_AUDIO_DURATION=600
      - LLM_MAX_TOKENS=2000
      - MAX_FILE_SIZE_MB=50
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
          
    networks:
      - scribe-network

networks:
  scribe-network:
    driver: bridge