version: '3.8'

services:
  scribe-engine:
    image: dietmarw/scribe-engine:latest
    container_name: scribe-engine-pi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    restart: unless-stopped
    # ARM64 resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'

  # Lightweight monitoring für Raspberry Pi
  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: scribe-engine-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=1d' # 1 day retention
    restart: unless-stopped

